### ISSUE TITLE
Criar conceito Transition

### ISSUE THREAD

**Issue by leonardofl** [poli-libras/sign-model#7]
Considerando o milestone de implementar o movimento circular, me parece que o melhor é usar o novo conceito de "Transition".

Hoje, o movimento e o movimento circular tem alguns problemas. Os atributos locationAt e startsInLocation são difíceis de entender (acho que startsInLocation  nem deveria mais existir); na formulação do sign model 2.0 o RoundSegment possui o atributo initialMovementVector, que além de difícil de usar, invalida o atributo direction herdado de Segment (modelo desnormalizado).

Então a ideia é acabar com o conceito de movimento. Mais simples pensar que temos Poses (o que hoje seriam os símbolos), e que nos movemos entre essas Poses por meio de Transições. A transição padrão é a transição linear, que não precisa ser configurada. Mas a transição pode ser também circular.

Assim, teríamos a classe Transition, com os atributos speed e interpolationType, e a classe RoundTransition, herdando de Transition, apenas com o atributo roundPlane, para especificar se a circunferência é feita no plano vertical ou horizontal. Teoricamente isso é limitante, pois poder-se-ia fazer circunferências em outros planos do espaço. Mas vamos começar simples assim, porque talvez isso já dê conta na prática dos sinais com movimento circular.

Minha ideia é primeiro inserir a transição no modelo e fazer ela funcionar para o movimento circular. Posteriormente refatoro os sinais que hoje usam movimentos para usarem apenas transições. Em seguida, acabo com o conceito de movimento.

Como essas alterações são possivelmente críticas, devo fazer em branches novas.

**Comment by leonardofl** [comment]
Parece bom @MLK3 ?

**Comment by MLK3** [comment]
Parece bom. Acho que fica mais alinhado com como são feitas animações em geral

**Comment by leonardofl** [comment]
Então... percebi novamente que apenas o "round plane" não basta para especificar uma transição circular (assim como não bastava para o movimento circular). Poderíamos tentar colocar um atributo a mais no RoundTransition com enums do tipo "pra dentro", "pra fora", mas isso não soa bem... já tinha falado acima sobre os potenciais problemas de limitação do "round plane: horizontal vs vertical". Com essa coisas a mais, ficaríamos ainda mais limitado, e com um modelo longe de ser elegante.

Relembrando que na adoção de rotX, rotY e rotZ no Symbol, em contraposição às enumerações Orientação, Plano e Rotação, consideramos que embora interfaces de alto nível (como WikiLibras) possam privilegiar apresentações mais convenientes a humanos, isso não precisa necessariamente se refletir no modelo lido pelo VJ, que pode ser mais baixo nível.

Considerando essas coisas, acho que voltamos a ideia de que um movimento (no caso transição) possa ser especificado por um initial move vector mais os pontos de partida e chegada. Esse vetor de movimento inicial indica de uma vez só o "plano" e a "direção" da transição circular. 

Vou colocar alguns desenhos pra ajudar a explicar como o initial move vector (v) determina a trajetória da mão.

**Comment by leonardofl** [comment]
![2017-08-15 17 35 08-1](https://user-images.githubusercontent.com/362813/29335249-699abaaa-81e0-11e7-844e-9116b1e96e07.jpg)

A ideia da figura é mostrar como A (ponto inicial), B (ponto final) e v definem um caminho percorrido sobre uma elipse.

**Comment by leonardofl** [comment]
Poderíamos usar pontos de controle, mas na acredito que o initial move vector será mais prático. Isso por que na prática provavelmente utilizaremos apenas vetores perpendiculares aos planos x, y e z, que são razoavelmente intuitivos. Colocar pontos de controle acho que deixaria o modelo mais complicado. Com pontos de controle quero dizer que a trajetória de A à B deve passar por um ponto de controle C, e daí deriva-se uma curva de Bezier que passa por A, B e C.

O initial move vector (v) tem potencial também para determinar a forma de uma elipse (não somente uma circunferência) que a mão deve percorrer para ir de A a B. Se v é perpendicular à reta AB, então o movimento é circular. No limite, se v é paralelo à AB, então o movimento é linear (embora na prática, é mais fácil omitir v do modelo para transições lineares).

**Comment by leonardofl** [comment]
![elipse](https://user-images.githubusercontent.com/362813/29335504-4c597764-81e1-11e7-8975-ed6a8e8bbebc.jpg)

Sendo que temos A, B, então temos a. O desafio é encontrar b.

**Comment by leonardofl** [comment]
Tenho minhas dúvidas se na "ponta da elipse" a reta tangente não será sempre paralela ao eixo menor da elipse, mas seja como for, acho que bolei um algoritmo para encontrar um b, dados A, B e v.

Considere que v = (0, 1), então queremos b = a. Caso v = (0, 0), então b = 0. Já se v (0, -1), b = -a.

Esses valores mais os desenhos anteriores parecem sugerir que b é proporcional à norma da projeção de v sobre o eixo y.

Então definindo vy = (0, 1), o vetor do eixo y, temos algo como b = a * |proj(v, vy)|, onde proj(v, vy) é a projeção de v em vy. Só que essa definição não está boa, porque não leva em conta os negativos.

Se pegarmos o vetor v = (0, -1) chegaremos que p = proj(v, vy) = (0, -1). Como a projeção sempre terá 0 em p[0], então podemos dizer que b = p[1], nesse caso b = p[1] = -1.

Claro que esse raciocínio todo é bidimensional e ainda é preciso generalizar para 3D.

**Comment by leonardofl** [comment]
Embora as elipses não nos sejam extremamente necessárias, nesse caso não me parece que nos restringirmos a circunferências irá simplificar o problema de definir a equação da circunferência dados A, B e v, uma vez que talvez isso só estaria na prática restringindo os valores de v.

**Comment by leonardofl** [comment]
Bom, próximo passo é pensar em 3D. Algo me diz que quando pensar em 3D vou jogar muita coisa fora aqui hehe.

Voltando à circunferência... ou melhor dizendo, um arco sobre uma esfera, temos que x^2 + y^2 + z^2 = r^2. Ao movermos x, precisamos de uma restrição de um plano para mover y e z. Talvez v possa servir para definir esse plano, junto com AB. Mas aí ainda tem a questão do sentido, pois há duas metades de uma circunferência...

**Comment by leonardofl** [comment]
Insights @MLK3 @fabiopicchi ?
=D

**Comment by leonardofl** [comment]
Humm... agora tentei pensar no 3D. E pra tentar simplificar voltei a pensar na esfera.

Problema: ir do ponto A ao ponto B caminhando sobre uma esfera que contém A e B e cujo centro é o ponto médio de A e B.

Vamos montar um sistema de coordenadas local (x,y,z), sendo C o ponto médio entre A e B: A = (-1, 0, 0), B = (1, 0, 0) e C = (0, 0, 0). Obs: isso significa que os pontos A e B estão sobre o eixo x.

Vamos considerar que gama (g de globo) é a circunferência com centro em C e de raio 1. E beta é o plano tangente a gama que passa por A.

Vamos definir nossa trajetória sobre a esfera em função de v, um vetor em beta.

Consideremos algumas possibilidades:

![globo](https://user-images.githubusercontent.com/362813/29341173-21723f82-81f9-11e7-89d0-6f5566703e91.jpg)

v1 = (0, 0, 1) => y = 0 => x^2 + z^2 = 1 => z = + sqrt(1 - x^2)
v2 = (0, 0, -1) => y = 0 => x^2 + z^2 = 1 => z = - sqrt(1 - x^2)

Em ambos os casos, para percorrer o arco da circunferência basta interpolar linearmente x, fazer y = 0 e calcular z em função de x.

v3 = (0, 1, 0) => z = 0 => x^2 + y^2 = 1 => y = + sqrt(1 - x^2)
v4 = (0, -1, 0) => z = 0 => x^2 + y^2 = 1 => y = - sqrt(1 - x^2)

Em ambos os casos, para percorrer o arco da circunferência basta interpolar linearmente x, fazer z = 0 e calcular y em função de x.

Nesses casos foi fácil porque uma das coordenadas (y ou z) ficavam zeradas.

Mas eu ainda não sei o que faria no caso de v5:

![globo-v5](https://user-images.githubusercontent.com/362813/29341358-2f3d03b2-81fa-11e7-8d2b-ceeeb2ecd593.jpg)

Como vou coordenar a variação de y e z?

Porém, se nos limitarmos a v1, v2, v3 e v4, podemos definir o caminho sobre a esfera com a numeração: +Y, -Y, +Z, -Z. E talvez isso seja um começo razoável.

**Comment by leonardofl** [comment]
Atualizando como anda a epopeia:

Estou usando uns bloquinhos do processing pra fazer experiências e consegui mover um bloquinho em movimento circular em duas dimensões (planos Oxy, Oxz e Oyz). Tomando como exemplo o movimento circular em Oxy, eu mantive z fixo. O movimento circular foi obtido basicamente com

```
x = centerX + cos(angulo) * raio;
y = centerY + sin(angulo) * raio;
```

onde `angulo` varia de 0 a 2*PI.

Aí tentei fazer z variar de acordo com a equação da esfera: (z-z0)^2 + (x-x0)^2 + (y-y0)^2 = R^2, mas nessa tentativa rolou uns efeitos estranhos q parecem q tem a ver com arredondamentos.

Aí oq estou tentando fazer agora é interpolar z linearmente enquanto x e y seguem circularmente. Ainda não tive um resultado mt bom, mas ainda tenho q tentar o seguinte: dividir a variação de z em duas fases: com o angulo de 0 a PI z aumenta e com o ângulo de PI a 2*PI, z retrocede.

Links das experiências:
https://github.com/poli-libras/virtual-jonah/blob/transition/src/br/usp/libras/sanbox/CircularMovementIn2D.java
https://github.com/poli-libras/virtual-jonah/blob/transition/src/br/usp/libras/sanbox/CircularMovementIn3D.java

Link que pode ajudar:
https://www.youtube.com/watch?v=8rhiQ96EF6g&lc=z22fvjnotzqyt3yzm04t1aokglujp5t4rq1hbwgamheqbk0h00410.1506985114496078

**Comment by leonardofl** [comment]
Feito (ao longo de vários commits): 

* https://github.com/poli-libras/sign-model/blob/master/src/br/usp/libras/sign/transition/Transition.java
* https://github.com/poli-libras/sign-model/blob/master/src/br/usp/libras/sign/transition/Path.java
